apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrocd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrocd-demo
  template:
    metadata:
      labels:
        app: agrocd-demo
    spec:
      containers:
      - name: agrocd-demo
        image: docker push arshadpasha111/agrocd-demo:tagname
        ports:
        - containerPort: 3000

